"""Event keyword -> closed-catalogue category mapping (brief section 8: semantic
equivalence, e.g. "Anchor Aweigh" / "Anchor Up" / "Heave Up Anchor" are the same
event). This is deliberately a plain data table, not prompt text — extending it (a
future EventSynonymMap, SYSTEM_ARCHITECTURE.md section 5) is a data change, not a
code change.

Order matters: app.extraction.sof_extraction.heuristic_extractor tries these in
order and takes the first match, so more specific phrases are listed before more
generic ones that could otherwise shadow them.
"""
from __future__ import annotations

import re


def _kw(*phrases: str) -> re.Pattern:
    return re.compile("|".join(re.escape(p) for p in phrases))


EVENT_KEYWORDS: list[tuple[re.Pattern, str]] = [
    (_kw("NOTICE OF READINESS TENDERED", "NOR TENDERED"), "NOR_TENDERED"),
    (_kw("NOTICE OF READINESS ACCEPTED", "NOR ACCEPTED"), "NOR_ACCEPTED"),
    (_kw("ANCHOR DROPPED", "DROPPED ANCHOR", "ANCHORED"), "ANCHOR_DROPPED"),
    (_kw("ANCHOR AWEIGH", "ANCHOR UP", "HEAVE UP ANCHOR", "HEAVING UP ANCHOR"), "ANCHOR_AWEIGH"),
    (_kw("PILOT ON BOARD", "PILOT BOARDED", "EMBARKED PILOT"), "PILOT_ON_BOARD"),
    (_kw("COMMENCED INWARD PASSAGE", "INWARD PASSAGE COMMENCED"), "COMMENCED_INWARD_PASSAGE"),
    (_kw("TUG(S) MADE FAST", "TUGS MADE FAST", "TUG OPERATIONS"), "TUG_OPERATIONS"),
    (_kw("ALL FAST"), "ALL_FAST"),
    (_kw("SECURELY MOORED", "VESSEL MOORED", "FULLY MOORED"), "SECURELY_MOORED"),
    (_kw("GANGWAY IN PLACE", "GANGWAY DOWN", "GANGWAY RIGGED"), "GANGWAY_IN_PLACE"),
    (_kw("AUTHORITIES ON BOARD", "AUTHORITIES BOARDED"), "AUTHORITIES_ON_BOARD"),
    (_kw("AUTHORITIES DISEMBARKED", "AUTHORITIES LEFT VESSEL"), "AUTHORITIES_DISEMBARKED"),
    (_kw("FREE PRATIQUE"), "FREE_PRATIQUE"),
    (_kw("HOSE CONNECTION", "HOSES CONNECTED", "HOSE CONNECTED"), "HOSE_CONNECTION"),
    (_kw("COMMENCED LOADING", "LOADING COMMENCED", "COMMENCED LOAD"), "COMMENCED_LOADING"),
    (_kw("COMMENCED DISCHARGING", "DISCHARGING COMMENCED", "COMMENCED DISCHARGE"), "COMMENCED_DISCHARGING"),
    (_kw("CARGO STOPPED", "CARGO SUSPENDED", "STOPPED LOADING", "STOPPED DISCHARGING"), "CARGO_STOPPED"),
    (_kw("CARGO RESUMED", "RESUMED LOADING", "RESUMED DISCHARGING"), "CARGO_RESUMED"),
    (_kw("COMPLETED LOADING", "LOADING COMPLETED", "COMPLETION OF LOADING"), "COMPLETED_LOADING"),
    (_kw("COMPLETED DISCHARGING", "DISCHARGING COMPLETED", "COMPLETED DISCHARGE"), "COMPLETED_DISCHARGING"),
    (_kw("HOSES DISCONNECTED", "HOSE DISCONNECTED"), "HOSES_DISCONNECTED"),
    (_kw("COMMENCED BUNKERING", "BUNKERING", "BUNKERS SUPPLIED"), "BUNKERING"),
    (_kw("COMMENCED BALLASTING", "BALLASTING"), "BALLASTING"),
    (_kw("DEBALLASTING", "DE-BALLASTING"), "DEBALLASTING"),
    (_kw("DISCHARGING SLOPS", "SLOPS DISCHARGE"), "SLOPS"),
    (_kw("TANK WASHING", "TANK CLEANING"), "TANK_WASHING"),
    (_kw("SHIP LINING UP", "LINING UP"), "SHIP_LINING_UP"),
    (_kw("DRAINING PUMPS", "DRAINING PIPELINES", "DRAINING LINES"), "DRAINING_PUMPS_PIPELINES"),
    (_kw("LINE FLUSHING", "FLUSHING LINES"), "LINE_FLUSHING"),
    (_kw("COMMENCED SHIFTING", "SHIFTING TO", "SHIFTED TO", "SHIFTING"), "SHIFTING"),
    (_kw("UNBERTHING", "UNBERTHED", "CAST OFF"), "UNBERTHING"),
    (_kw("REBERTHING", "REBERTHED"), "REBERTHING"),
    (
        _kw(
            "BAD WEATHER", "HEAVY WEATHER", "ADVERSE WEATHER", "INCLEMENT WEATHER",
            "HIGH WINDS", "STRONG WINDS", "SWELL", "FOG",
        ),
        "WEATHER",
    ),
    (_kw("PORT CLOSED", "PORT CLOSURE"), "PORT_CLOSURE"),
    (_kw("BERTH NOT AVAILABLE", "BERTH UNAVAILABLE"), "BERTH_UNAVAILABLE"),
    (_kw("WAITING FOR BERTH", "AWAITING BERTH"), "WAITING_BERTH"),
    (_kw("AWAITING CARGO DOCUMENTS", "WAITING FOR CARGO DOCUMENTS"), "AWAITING_CARGO_DOCUMENTS"),
    (_kw("WAITING FOR CARGO", "AWAITING CARGO"), "WAITING_CARGO"),
    (_kw("WAITING FOR INSTRUCTIONS", "AWAITING INSTRUCTIONS"), "WAITING_INSTRUCTIONS"),
    (_kw("VESSEL BREAKDOWN", "ENGINE BREAKDOWN", "MAIN ENGINE FAILURE"), "VESSEL_BREAKDOWN"),
    (
        _kw("SHORE BREAKDOWN", "SHORE EQUIPMENT BREAKDOWN", "SHORE MACHINERY BREAKDOWN", "TERMINAL BREAKDOWN"),
        "SHORE_EQUIPMENT_BREAKDOWN",
    ),
    (
        _kw(
            "TUG STRIKE", "PILOT STRIKE", "CREW STRIKE", "STRIKE", "LABOUR DISPUTE",
            "GO SLOW", "WORK TO RULE", "LOCK-OUT", "LOCKOUT", "STOPPAGE",
        ),
        "STRIKE",
    ),
    (_kw("CHARTERERS DELAY", "CHARTERER'S DELAY", "FOR CHARTERERS ACCOUNT"), "CHARTERERS_DELAY"),
    (_kw("ARRIVED AT ANCHORAGE", "ANCHORAGE ARRIVAL"), "ARRIVAL_ANCHORAGE"),
    (_kw("VESSEL ARRIVED", "ARRIVED AT", "ARRIVAL"), "ARRIVAL"),
    (_kw("VESSEL SAILED", "SAILED FROM", "DEPARTURE"), "DEPARTURE"),
]
