"""initial schema

Revision ID: 944b78403d4e
Revises: 
Create Date: 2026-08-27 20:39:54.983253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '944b78403d4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('previous_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('time_impact', sa.String(), nullable=True),
    sa.Column('financial_impact', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rule_version_id', sa.String(), nullable=True),
    sa.Column('calculation_version_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_set_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_definition_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_count_factor', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('demurrage_rate_factor', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('scope_ref_id', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('source_clause_id', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('supersedes_version_id', sa.String(), nullable=True),
    sa.Column('requires_manual_confirmation', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voyages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vessel_name', sa.String(), nullable=False),
    sa.Column('imo_number', sa.String(), nullable=True),
    sa.Column('voyage_number', sa.String(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('sw_user', sa.String(), nullable=True),
    sa.Column('rt_organization', sa.String(), nullable=True),
    sa.Column('load_port', sa.String(), nullable=True),
    sa.Column('discharge_port', sa.String(), nullable=True),
    sa.Column('terminal', sa.String(), nullable=True),
    sa.Column('berth', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('laycan_from', sa.DateTime(), nullable=True),
    sa.Column('laycan_to', sa.DateTime(), nullable=True),
    sa.Column('allowed_laytime_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('allowed_laytime_unit', sa.String(), nullable=False),
    sa.Column('demurrage_rate_type', sa.String(), nullable=False),
    sa.Column('demurrage_rate_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('daylight_restriction_enabled', sa.Boolean(), nullable=False),
    sa.Column('daylight_start', sa.String(), nullable=True),
    sa.Column('daylight_end', sa.String(), nullable=True),
    sa.Column('sealine', sa.Boolean(), nullable=False),
    sa.Column('lightering', sa.Boolean(), nullable=False),
    sa.Column('transshipment', sa.Boolean(), nullable=False),
    sa.Column('nor_allowance_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('workflow_state', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('rule_set_version_id', sa.String(), nullable=False),
    sa.Column('event_snapshot_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual_override_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculation_engine_version', sa.String(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integrity_ok', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_version_id'], ['rule_set_versions.id'], ),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sha256_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(), nullable=False),
    sa.Column('original_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_time_count_factor', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('new_demurrage_rate_factor', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('supporting_clause_id', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voyage_id', sa.String(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('terminal', sa.String(), nullable=True),
    sa.Column('berth', sa.String(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_set_version_rules',
    sa.Column('rule_set_version_id', sa.String(), nullable=False),
    sa.Column('rule_version_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_version_id'], ['rule_set_versions.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.PrimaryKeyConstraint('rule_set_version_id', 'rule_version_id')
    )
    op.create_table('sof_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('port_call_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('source_text', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_status', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('parent_event_id', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['port_call_id'], ['port_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sof_event_id', sa.String(), nullable=False),
    sa.Column('field_changed', sa.String(), nullable=False),
    sa.Column('previous_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sof_event_id'], ['sof_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_evidence')
    op.drop_table('sof_events')
    op.drop_table('rule_set_version_rules')
    op.drop_table('port_calls')
    op.drop_table('manual_overrides')
    op.drop_table('documents')
    op.drop_table('calculation_versions')
    op.drop_table('voyages')
    op.drop_table('rule_versions')
    op.drop_table('rule_set_versions')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
