"""voyage rule set assignment

Revision ID: ba50e79e206c
Revises: 944b78403d4e
Create Date: 2026-08-27 20:42:13.892340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba50e79e206c'
down_revision: Union[str, Sequence[str], None] = '944b78403d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voyages', sa.Column('rule_set_version_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'voyages', 'rule_set_versions', ['rule_set_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voyages', type_='foreignkey')
    op.drop_column('voyages', 'rule_set_version_id')
    # ### end Alembic commands ###
