// Mirrors the closed catalogue in backend/app/domain/facts/models.py — keep in sync.
export const EVENT_CATEGORIES = [
  "ARRIVAL", "ARRIVAL_ANCHORAGE", "NOR_TENDERED", "NOR_ACCEPTED", "ANCHOR_DROPPED",
  "ANCHOR_AWEIGH", "PILOT_ON_BOARD", "COMMENCED_INWARD_PASSAGE", "TUG_OPERATIONS",
  "ALL_FAST", "SECURELY_MOORED", "GANGWAY_IN_PLACE", "AUTHORITIES_ON_BOARD",
  "AUTHORITIES_DISEMBARKED", "FREE_PRATIQUE", "HOSE_CONNECTION", "COMMENCED_LOADING",
  "COMMENCED_DISCHARGING", "CARGO_STOPPED", "CARGO_RESUMED", "COMPLETED_LOADING",
  "COMPLETED_DISCHARGING", "HOSES_DISCONNECTED", "BUNKERING", "BALLASTING",
  "DEBALLASTING", "SLOPS", "TANK_WASHING", "SHIP_LINING_UP", "DRAINING_PUMPS_PIPELINES",
  "LINE_FLUSHING", "SHIFTING", "UNBERTHING", "REBERTHING", "WEATHER", "PORT_CLOSURE",
  "WAITING_BERTH", "BERTH_UNAVAILABLE", "WAITING_CARGO", "AWAITING_CARGO_DOCUMENTS",
  "WAITING_INSTRUCTIONS", "VESSEL_BREAKDOWN", "SHORE_EQUIPMENT_BREAKDOWN", "STRIKE",
  "CHARTERERS_DELAY", "DEPARTURE", "OTHER",
] as const;

export const CONFIDENCE_STATUSES = [
  "CONFIRMED", "PROBABLE", "UNKNOWN", "CONFLICTING_INFORMATION", "NEEDS_REVIEW",
] as const;

export const EVENT_STATUSES = ["EXTRACTED", "EDITED", "CONFIRMED", "REJECTED"] as const;
